download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","ExploratoryPA1.zip")
data <- read.table(unzip("ExploratoryPA1.zip"),header=TRUE,sep=";",na.strings = "?",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
newdata <- data[data$Date == "2007-02-01" | data$Date == "2007-02-02",]
newdata$DateTime <- as.POSIXct(paste(newdata$Date, newdata$Time), format="%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
par(mar = c(4,4,2,2))
plot(newdata$DateTime,newdata$Global_active_power,type="l",xlab = "", ylab = "Global Active Power (kilowatts)")
plot(newdata$DateTime,newdata$Voltage,type="l",xlab = "datetime", ylab = "Voltage")
plot(newdata$DateTime,newdata$Sub_metering_1,type="n",xlab = "", ylab = "Energy sub metering")
points(newdata$DateTime,newdata$Sub_metering_1,type = "l",col = "black")
points(newdata$DateTime,newdata$Sub_metering_2,type = "l",col = "red")
points(newdata$DateTime,newdata$Sub_metering_3,type = "l",col = "blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"),lwd=1,bty="n",y.intersp=1)
plot(newdata$DateTime,newdata$Global_reactive_power,type="l",xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
